### PR TITLE
Update kl_699_sutrasthana-1-31.txt till 1.6.7

### PR DESCRIPTION
**Pull request by Paras-Sanskrit**

### CODE REVIEW

**Comment by wujastyk** [comment]
Dear Paras, I am merging your updates.  I notice that you have added avagraha to a number of places; are these avagrahas really in the KL 699 manuscript?  If not, they shouldn't be added.

**Comment by Paras-Sanskrit** [comment]
Dear Sir,

K doesn't have avagrahas for the most part. But had told earlier that one
should add the avagrahas for better appearance of the text.
Was it only meant for provisional edition?

Regards,
Paras

**Comment by wujastyk** [comment]
> Dear Sir, K doesn't have avagrahas for the most part. But had told earlier that one should add the avagrahas for better appearance of the text. Was it only meant for provisional edition? Regards, Paras

Yes, that's right.  In the provisional edition we say "prathamo 'dhyāyaḥ"  but in the manuscript transcription files we say "prathamo dhyāyaḥ"  (with the space).  The manuscript transcriptions should be as close as possible to what the scribe actually wrote.

Best,
Dominik

**Comment by Paras-Sanskrit** [comment]
Ok, Sir. Got it.

Regards,
Paras

**Pull request merged**
