### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by ankleb**
- updates to the folio concordance of NAK 1-1079

- Added transcription of 1.14 in NAK 1-1079
- added several changes to 1.14 and 1.21 in 5-333 and KL 699

- updates to the edition and transcriptions of 6.38
- updates to the translation of 6.38

### CODE REVIEW

**Comment by wujastyk** [comment]
Merged.  Thanks!

**Comment by wujastyk** [comment]
PS, Github said to me about your pull request:

image

I don't know what this means, and I ignored it.

**Comment by wujastyk** [comment]
When  pulled the changes to my own disk, I saw that you have been changing the file permissions:

image

This mode chaning is not necessary.  Just leave the file permissions alone: changing them is likely to cause difficulties for everyone else.  100644 is the standard permission setting for a file.  100755 is the setting for a directory (=folder). n

**Comment by ankleb** [comment]
to tell you the truth, I have no idea how I changed the file permissions, because I am not even entirely sure what file permissions are. Perhaps, I have changed something unknowingly. Please let me know if you notice this again and I try to think of what me causing this problem.

best,
Andrey

**Pull request merged**
